// .claude/workflows/review-changes.js — reusable review→verify pipeline.
// Generated by the swe-flow `workflow-author` skill as its dogfood example. Reviews the
// current branch diff across independent dimensions, then adversarially verifies each
// finding, surfacing only the issues that survive refutation. pipeline() has NO barrier:
// a dimension's findings verify as soon as that dimension's review completes.
//
// MANDATORY FALLBACK — workflows are research-preview and globally disableable
// (disableWorkflows / CLAUDE_CODE_DISABLE_WORKFLOWS=1) and cannot be bundled in a plugin.
// If this does not run, drive the same order BY HAND: for each dimension dispatch
// swe-flow:reviewer over the diff; for each finding, dispatch a second swe-flow:reviewer to
// refute it; keep only the findings that survive. govkit verify + the PreToolUse hook gate
// every governed doc regardless — this workflow only triages code review, it never flips a
// status.
//
// CONSTRAINTS: this script has NO filesystem/shell access — the reviewer agents read the
// diff. It composes ONLY existing swe-flow agents + reviewer verdicts; it dispatches no new
// agent types. agentType is plugin-namespaced (swe-flow:reviewer) so the plugin must be
// installed.

export const meta = {
  name: "review-changes",
  description:
    "Review the current branch diff across {correctness, reuse, governance} via swe-flow:reviewer, adversarially verify each finding, and surface only the issues that survive refutation.",
  phases: [
    { title: "Review", detail: "one reviewer per dimension over the diff" },
    { title: "Verify", detail: "refute each finding; keep only survivors" },
  ],
};

const REVIEWER = "swe-flow:reviewer";

const FINDINGS_SCHEMA = {
  type: "object",
  required: ["findings"],
  properties: {
    findings: {
      type: "array",
      items: {
        type: "object",
        required: ["title", "file", "detail"],
        properties: {
          title: { type: "string" },
          file: { type: "string" },
          detail: { type: "string" },
        },
      },
    },
  },
};

const VERDICT_SCHEMA = {
  type: "object",
  required: ["refuted", "reason"],
  properties: {
    refuted: { type: "boolean" },
    reason: { type: "string" },
  },
};

// The example IS the shape, not a fixed artifact: pass your own dimensions via `args`,
// or fall back to these three. Same skeleton reviews any set of concerns over the diff.
const DIMENSIONS = (args && args.dimensions) || [
  { key: "correctness", prompt: "Find correctness bugs the diff introduces." },
  { key: "reuse", prompt: "Find duplication, missed reuse, or needless complexity in the diff." },
  {
    key: "governance",
    prompt:
      "Find governance gaps: a governed doc (docs/product|rfc|adr|issues) touched without " +
      "complete front-matter / INDEX sync / start-status discipline, or a public-surface change " +
      "(a CLI flag, a skill, a plugin export) made with no RFC/ADR.",
  },
];

phase("Review");
const reviewed = await pipeline(
  DIMENSIONS,
  (d) =>
    agent(
      `You are swe-flow:reviewer (read-only). Inspect the full working state: the committed branch ` +
        `diff (git diff against the base branch) AND uncommitted/untracked changes (git status + git ` +
        `diff for tracked, read new files directly) — untracked files are NOT in git diff. ${d.prompt} ` +
        `Return each issue as a finding {title, file, detail}.`,
      { label: `review:${d.key}`, phase: "Review", schema: FINDINGS_SCHEMA, agentType: REVIEWER },
    ),
  (review, d) =>
    parallel(
      (review.findings || []).map((f) => () =>
        agent(
          `You are swe-flow:reviewer (read-only). Try to REFUTE this ${d.key} finding from the diff: ` +
            `"${f.title}" in ${f.file} — ${f.detail}. Default to refuted=true if you cannot reproduce it.`,
          { label: `verify:${d.key}`, phase: "Verify", schema: VERDICT_SCHEMA, agentType: REVIEWER },
        ).then((v) => ({ ...f, dimension: d.key, survived: Boolean(v) && v.refuted === false })),
      ),
    ),
);

const issues = reviewed.flat().filter(Boolean).filter((f) => f.survived);
log(
  `[review-changes] ${issues.length} confirmed issue(s) after refutation: ` +
    (issues.map((f) => `${f.dimension}:${f.file} — ${f.title}`).join(" | ") || "none"),
);
